name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/wyvox/action-setup-pnpm
      - uses: wyvox/action-setup-pnpm@v3
        with: { node-version: 22, pnpm-version: 10 }

        # use astro check for issues
      - name: Run check
        run: pnpm astro check

        # ensure build works
      - name: Run build
        run: pnpm build
